
Showing logs for build [32mvicky-socs-test-python-jenkinsx-l7g6r-1[0m stage [32mfrom-build-pack[0m and container [32mstep-credential-initializer-qrskl[0m
{"level":"warn","ts":1584611267.8534603,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1584611267.8538976,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mvicky-socs-test-python-jenkinsx-l7g6r-1[0m stage [32mfrom-build-pack[0m and container [32mstep-working-dir-initializer-4hhqx[0m
{"level":"warn","ts":1584611268.8460314,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1584611268.8498366,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}

Showing logs for build [32mvicky-socs-test-python-jenkinsx-l7g6r-1[0m stage [32mfrom-build-pack[0m and container [32mstep-place-tools[0m

Showing logs for build [32mvicky-socs-test-python-jenkinsx-l7g6r-1[0m stage [32mfrom-build-pack[0m and container [32mstep-git-source-vicky-socs-test-python-jenkinsx-l7g6r-rjgnl[0m
{"level":"warn","ts":1584611272.9325495,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1584611275.6104412,"logger":"fallback-logger","caller":"git/git.go:103","msg":"Successfully cloned https://github.com/vicky-socs/test-python-jenkinsx.git @ master in path /workspace/source"}

Showing logs for build [32mvicky-socs-test-python-jenkinsx-l7g6r-1[0m stage [32mfrom-build-pack[0m and container [32mstep-git-merge[0m
Using SHAs from PULL_REFS=staging:ca5033b00cb7be45c89d630cf44d908853c2ba2f,8:f6f72a9801abfd1eb16ecaf6bf5224c16b33c060
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git fetch origin --unshallow f6f72a9801abfd1eb16ecaf6bf5224c16b33c060: ca5033b00cb7be45c89d630cf44d908853c2ba2f:
DEBUG: ran git fetch --unshallow origin f6f72a9801abfd1eb16ecaf6bf5224c16b33c060: ca5033b00cb7be45c89d630cf44d908853c2ba2f: in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git branch
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git branch staging
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git checkout staging
DEBUG: ran git checkout staging in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git reset --hard ca5033b00cb7be45c89d630cf44d908853c2ba2f
DEBUG: ran git reset --hard ca5033b00cb7be45c89d630cf44d908853c2ba2f in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git clean -fd .
DEBUG: ran clean --force -d . in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git merge f6f72a9801abfd1eb16ecaf6bf5224c16b33c060
DEBUG: ran git merge f6f72a9801abfd1eb16ecaf6bf5224c16b33c060 in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git log --format=%H%x1f%an%x1f%ae%x1f%cn%x1f%ce%x1f%s%n%b%x1e ca5033b00cb7be45c89d630cf44d908853c2ba2f..HEAD
Merged SHA f6f72a9801abfd1eb16ecaf6bf5224c16b33c060 with commit message 'staging.yml deleted' into base branch staging

Showing logs for build [32mvicky-socs-test-python-jenkinsx-l7g6r-1[0m stage [32mfrom-build-pack[0m and container [32mstep-build-python-unittest[0m

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK

Showing logs for build [32mvicky-socs-test-python-jenkinsx-l7g6r-1[0m stage [32mfrom-build-pack[0m and container [32mstep-build-container-build[0m
[36mINFO[0m[0000] Downloading base image python:onbuild        
2020/03/19 09:47:59 No matching credentials were found, falling back on anonymous
[36mINFO[0m[0002] Error while retrieving image from cache: getting file info: stat /workspace/sha256:43780a8431c53f4afd734ad795e03127c0c607337a60639c5903a51a03535c22: no such file or directory 
[36mINFO[0m[0002] Downloading base image python:onbuild        
2020/03/19 09:48:02 No matching credentials were found, falling back on anonymous
[36mINFO[0m[0004] Executing 3 build triggers                   
[36mINFO[0m[0004] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0004] Checking for cached layer 685249416972.dkr.ecr.ap-south-1.amazonaws.com/todo/cache:20ed5631d983ab35ddcc4224cde40d34ba4dcc68c4ee26635bbf30d01c3c2af6... 
[36mINFO[0m[0005] Using caching version of cmd: RUN pip install --no-cache-dir -r requirements.txt 
[36mINFO[0m[0005] Using files from context: [/workspace/source] 
[36mINFO[0m[0005] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0005] cmd: EXPOSE                                  
[36mINFO[0m[0005] Adding exposed port: 8080/tcp                
[36mINFO[0m[0005] Skipping unpacking as no commands require it. 
[36mINFO[0m[0005] Taking snapshot of full filesystem...        
[36mINFO[0m[0005] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0005] COPY requirements.txt /usr/src/app/          
[36mINFO[0m[0005] Taking snapshot of files...                  
[36mINFO[0m[0005] RUN pip install --no-cache-dir -r requirements.txt 
[36mINFO[0m[0005] Found cached layer, extracting to filesystem 
[36mINFO[0m[0005] Taking snapshot of files...                  
[36mINFO[0m[0006] Using files from context: [/workspace/source] 
[36mINFO[0m[0006] COPY . /usr/src/app                          
[36mINFO[0m[0006] Taking snapshot of files...                  
[36mINFO[0m[0006] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0006] COPY requirements.txt .                      
[36mINFO[0m[0006] Taking snapshot of files...                  
[36mINFO[0m[0006] ENV PORT 8080                                
[36mINFO[0m[0006] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0006] EXPOSE 8080                                  
[36mINFO[0m[0006] cmd: EXPOSE                                  
[36mINFO[0m[0006] Adding exposed port: 8080/tcp                
[36mINFO[0m[0006] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0006] ENTRYPOINT ["python"]                        
[36mINFO[0m[0006] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0006] CMD ["app.py"]                               
[36mINFO[0m[0006] No files changed in this command, skipping snapshotting. 
2020/03/19 09:48:05 existing blob: sha256:06854774e2f35e4763103a446112c67322913a6177bea69eb49663e0166e6d6d
2020/03/19 09:48:05 existing blob: sha256:2d21c767035c4593de8bf7ad9781aa83ba110871d1a50871192f4e3480e6f11d
2020/03/19 09:48:05 existing blob: sha256:f0db43b9b8da254cebc77bf871006df01219e195b9853616b9f708f124a00f3a
2020/03/19 09:48:05 existing blob: sha256:e2c0fb34dff3a1d32346b92e53fb88a14d1987b402a2348cb379c039687fabe2
2020/03/19 09:48:05 existing blob: sha256:490280dbcfb772eb5731f059e38fcfacaeb75b4d005af7c249fd51926db2bd62
2020/03/19 09:48:05 existing blob: sha256:e96bc319bce0351d1157092352bc5f85f8800c745388e60e86d06dec99285b45
2020/03/19 09:48:06 pushed blob: sha256:5cb2578c94c527ec9bd8576c0645777bde9f57a07ed3344d73244f2731bd4521
2020/03/19 09:48:06 pushed blob: sha256:e68c684d311f7f41d7b8a4d59ca364fe1efe8ad65d1e09fb591ca46c8b9f0cc5
2020/03/19 09:48:06 pushed blob: sha256:5010210e4aa0b428af6086995163085e1fcd5141844bf9c30da39ab1e2c54f3d
2020/03/19 09:48:06 existing blob: sha256:e10b68fb77e6e91453cd4c1b02e2d77aa23a857cd8eb250617129d074478e1a5
2020/03/19 09:48:06 existing blob: sha256:1c7fe136a31e13a1c879245672184ced3b9fc590989ba42a522a57b071a9c1aa
2020/03/19 09:48:07 pushed blob: sha256:152e62453b752b57de6fdf0be6f8c83553df0d9be55fc731c865924039a4894b
2020/03/19 09:48:07 pushed blob: sha256:c026616d1d931170c36116d972ae75858c54f0a1346027cb9916e58f6bdc065a
2020/03/19 09:48:08 existing blob: sha256:ece825d3308bbf98f708d95475ccd880497a1e2979ff4ef2534d49049a18488f
2020/03/19 09:48:08 685249416972.dkr.ecr.ap-south-1.amazonaws.com/vicky-socs/test-python-jenkinsx:0.0.0-SNAPSHOT-PR-8-1: digest: sha256:c8220e26d827570b39ba93c896677bc491fe6ceb20e34fe14859827213386acb size: 2385

Showing logs for build [32mvicky-socs-test-python-jenkinsx-l7g6r-1[0m stage [32mfrom-build-pack[0m and container [32mstep-postbuild-post-build[0m
no CVE provider running in the current ** namespace so skip adding image to be analysed

Showing logs for build [32mvicky-socs-test-python-jenkinsx-l7g6r-1[0m stage [32mfrom-build-pack[0m and container [32mstep-promote-make-preview[0m
sed -i -e "s/version:.*/version: 0.0.0-SNAPSHOT-PR-8-1/" Chart.yaml
sed -i -e "s/version:.*/version: 0.0.0-SNAPSHOT-PR-8-1/" ../*/Chart.yaml
sed -i -e "s|repository:.*|repository: 685249416972.dkr.ecr.ap-south-1.amazonaws.com\/vicky-socs\/test-python-jenkinsx|" values.yaml
sed -i -e "s/tag:.*/tag: 0.0.0-SNAPSHOT-PR-8-1/" values.yaml
echo "  version: 0.0.0-SNAPSHOT-PR-8-1" >> requirements.yaml
** step helm build
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Adding missing Helm repo: storage.googleapis.com https://storage.googleapis.com/chartmuseum.jenkins-x.io
Successfully added Helm repository storage.googleapis.com.
Adding missing Helm repo: jenkins-x-chartmuseum http://jenkins-x-chartmuseum:8080
Successfully added Helm repository jenkins-x-chartmuseum.
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Adding missing Helm repo: chartmuseum.jenkins-x.io http://chartmuseum.jenkins-x.io
Successfully added Helm repository chartmuseum.jenkins-x.io.

Showing logs for build [32mvicky-socs-test-python-jenkinsx-l7g6r-1[0m stage [32mfrom-build-pack[0m and container [32mstep-promote-jx-preview[0m
Creating a preview
Created environment vicky-socs-test-python-jenkinsx-pr-8
Namespace **-vicky-socs-test-python-jenkinsx-pr-8 created 
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  config:
    domain: 3.6.244.161.nip.io
    exposer: Ingress
    http: "true"
preview:
  image:
    repository: 685249416972.dkr.ecr.ap-south-1.amazonaws.com/vicky-socs/test-python-jenkinsx
    tag: 0.0.0-SNAPSHOT-PR-8-1

Updating PipelineActivities vicky-socs-test-python-jenkinsx-pr-8-1 which has status Running
WARNING: preview application http://test-python-jenkinsx.**-vicky-socs-test-python-jenkinsx-pr-8.3.6.244.161.nip.io not available, error was 503 503 Service Temporarily Unavailable, delaying for: 1.070673276s
WARNING: preview application http://test-python-jenkinsx.**-vicky-socs-test-python-jenkinsx-pr-8.3.6.244.161.nip.io not available, error was 503 503 Service Temporarily Unavailable, delaying for: 1.195623845s
WARNING: preview application http://test-python-jenkinsx.**-vicky-socs-test-python-jenkinsx-pr-8.3.6.244.161.nip.io not available, error was 503 503 Service Temporarily Unavailable, delaying for: 3.07200378s
WARNING: preview application http://test-python-jenkinsx.**-vicky-socs-test-python-jenkinsx-pr-8.3.6.244.161.nip.io not available, error was 503 503 Service Temporarily Unavailable, delaying for: 1.783022906s
WARNING: preview application http://test-python-jenkinsx.**-vicky-socs-test-python-jenkinsx-pr-8.3.6.244.161.nip.io not available, error was 503 503 Service Temporarily Unavailable, delaying for: 7.468410696s
WARNING: preview application http://test-python-jenkinsx.**-vicky-socs-test-python-jenkinsx-pr-8.3.6.244.161.nip.io not available, error was 503 503 Service Temporarily Unavailable, delaying for: 4.245822445s
WARNING: preview application http://test-python-jenkinsx.**-vicky-socs-test-python-jenkinsx-pr-8.3.6.244.161.nip.io not available, error was 503 503 Service Temporarily Unavailable, delaying for: 7.668923244s
WARNING: preview application http://test-python-jenkinsx.**-vicky-socs-test-python-jenkinsx-pr-8.3.6.244.161.nip.io not available, error was 503 503 Service Temporarily Unavailable, delaying for: 13.301532569s
WARNING: preview application http://test-python-jenkinsx.**-vicky-socs-test-python-jenkinsx-pr-8.3.6.244.161.nip.io not available, error was 503 503 Service Temporarily Unavailable, delaying for: 19.312418843s
WARNING: preview application http://test-python-jenkinsx.**-vicky-socs-test-python-jenkinsx-pr-8.3.6.244.161.nip.io not available, error was 503 503 Service Temporarily Unavailable, delaying for: 33.130697797s
Preview application is now available at: http://test-python-jenkinsx.**-vicky-socs-test-python-jenkinsx-pr-8.3.6.244.161.nip.io
