
Showing logs for build [32mvicky-socs-test-python-jenkinsx-ct8sr-1[0m stage [32mfrom-build-pack[0m and container [32mstep-credential-initializer-dx6l8[0m
{"level":"warn","ts":1584536226.2070131,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1584536226.207684,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mvicky-socs-test-python-jenkinsx-ct8sr-1[0m stage [32mfrom-build-pack[0m and container [32mstep-working-dir-initializer-jvrjg[0m
{"level":"warn","ts":1584536226.6874564,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1584536226.6886857,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}

Showing logs for build [32mvicky-socs-test-python-jenkinsx-ct8sr-1[0m stage [32mfrom-build-pack[0m and container [32mstep-place-tools[0m

Showing logs for build [32mvicky-socs-test-python-jenkinsx-ct8sr-1[0m stage [32mfrom-build-pack[0m and container [32mstep-git-source-vicky-socs-test-python-jenkinsx-ct8sr-ltsft[0m
{"level":"warn","ts":1584536232.8468835,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1584536235.3755903,"logger":"fallback-logger","caller":"git/git.go:103","msg":"Successfully cloned https://github.com/vicky-socs/test-python-jenkinsx.git @ master in path /workspace/source"}

Showing logs for build [32mvicky-socs-test-python-jenkinsx-ct8sr-1[0m stage [32mfrom-build-pack[0m and container [32mstep-git-merge[0m
Using SHAs from PULL_REFS=staging:903df94cf9c19c56402b31238ef870fbd232ca11,4:9f713b4ec1faa51e9c761f1af747b4d954b27d0a
DEBUG: JX_LOG_LEVEL=error LC_ALL=C git fetch origin --unshallow 9f713b4ec1faa51e9c761f1af747b4d954b27d0a: 903df94cf9c19c56402b31238ef870fbd232ca11:
DEBUG: ran git fetch --unshallow origin 9f713b4ec1faa51e9c761f1af747b4d954b27d0a: 903df94cf9c19c56402b31238ef870fbd232ca11: in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git branch
DEBUG: JX_LOG_LEVEL=error LC_ALL=C git branch staging
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git checkout staging
DEBUG: ran git checkout staging in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git reset --hard 903df94cf9c19c56402b31238ef870fbd232ca11
DEBUG: ran git reset --hard 903df94cf9c19c56402b31238ef870fbd232ca11 in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git clean -fd .
DEBUG: ran clean --force -d . in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git merge 9f713b4ec1faa51e9c761f1af747b4d954b27d0a
DEBUG: ran git merge 9f713b4ec1faa51e9c761f1af747b4d954b27d0a in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git log --format=%H%x1f%an%x1f%ae%x1f%cn%x1f%ce%x1f%s%n%b%x1e 903df94cf9c19c56402b31238ef870fbd232ca11..HEAD
Merged SHA 120501c1543281fab380d5dfbc27e2b613b03f74 with commit message 'Merge commit '9f713b4ec1faa51e9c761f1af747b4d954b27d0a' into staging' into base branch staging
Merged SHA 9f713b4ec1faa51e9c761f1af747b4d954b27d0a with commit message 'Test' into base branch staging

Showing logs for build [32mvicky-socs-test-python-jenkinsx-ct8sr-1[0m stage [32mfrom-build-pack[0m and container [32mstep-build-python-unittest[0m

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK

Showing logs for build [32mvicky-socs-test-python-jenkinsx-ct8sr-1[0m stage [32mfrom-build-pack[0m and container [32mstep-build-container-build[0m
[36mINFO[0m[0000] Downloading base image python:onbuild        
2020/03/18 12:57:19 No matching credentials were found, falling back on anonymous
[36mINFO[0m[0002] Error while retrieving image from cache: getting file info: stat /workspace/sha256:43780a8431c53f4afd734ad795e03127c0c607337a60639c5903a51a03535c22: no such file or directory 
[36mINFO[0m[0002] Downloading base image python:onbuild        
2020/03/18 12:57:22 No matching credentials were found, falling back on anonymous
[36mINFO[0m[0004] Executing 3 build triggers                   
[36mINFO[0m[0004] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0004] Checking for cached layer 685249416972.dkr.ecr.ap-south-1.amazonaws.com/todo/cache:20ed5631d983ab35ddcc4224cde40d34ba4dcc68c4ee26635bbf30d01c3c2af6... 
[36mINFO[0m[0004] Using caching version of cmd: RUN pip install --no-cache-dir -r requirements.txt 
[36mINFO[0m[0004] Using files from context: [/workspace/source] 
[36mINFO[0m[0004] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0004] cmd: EXPOSE                                  
[36mINFO[0m[0004] Adding exposed port: 8080/tcp                
[36mINFO[0m[0004] Skipping unpacking as no commands require it. 
[36mINFO[0m[0004] Taking snapshot of full filesystem...        
[36mINFO[0m[0004] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0004] COPY requirements.txt /usr/src/app/          
[36mINFO[0m[0004] Taking snapshot of files...                  
[36mINFO[0m[0004] RUN pip install --no-cache-dir -r requirements.txt 
[36mINFO[0m[0004] Found cached layer, extracting to filesystem 
[36mINFO[0m[0004] Taking snapshot of files...                  
[36mINFO[0m[0005] Using files from context: [/workspace/source] 
[36mINFO[0m[0005] COPY . /usr/src/app                          
[36mINFO[0m[0005] Taking snapshot of files...                  
[36mINFO[0m[0005] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0005] COPY requirements.txt .                      
[36mINFO[0m[0005] Taking snapshot of files...                  
[36mINFO[0m[0005] ENV PORT 8080                                
[36mINFO[0m[0005] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0005] EXPOSE 8080                                  
[36mINFO[0m[0005] cmd: EXPOSE                                  
[36mINFO[0m[0005] Adding exposed port: 8080/tcp                
[36mINFO[0m[0005] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0005] ENTRYPOINT ["python"]                        
[36mINFO[0m[0005] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0005] CMD ["app.py"]                               
[36mINFO[0m[0005] No files changed in this command, skipping snapshotting. 
2020/03/18 12:57:24 existing blob: sha256:06854774e2f35e4763103a446112c67322913a6177bea69eb49663e0166e6d6d
2020/03/18 12:57:24 existing blob: sha256:f0db43b9b8da254cebc77bf871006df01219e195b9853616b9f708f124a00f3a
2020/03/18 12:57:24 existing blob: sha256:490280dbcfb772eb5731f059e38fcfacaeb75b4d005af7c249fd51926db2bd62
2020/03/18 12:57:24 existing blob: sha256:1c7fe136a31e13a1c879245672184ced3b9fc590989ba42a522a57b071a9c1aa
2020/03/18 12:57:24 existing blob: sha256:e96bc319bce0351d1157092352bc5f85f8800c745388e60e86d06dec99285b45
2020/03/18 12:57:24 existing blob: sha256:ece825d3308bbf98f708d95475ccd880497a1e2979ff4ef2534d49049a18488f
2020/03/18 12:57:24 existing blob: sha256:2d21c767035c4593de8bf7ad9781aa83ba110871d1a50871192f4e3480e6f11d
2020/03/18 12:57:24 existing blob: sha256:e10b68fb77e6e91453cd4c1b02e2d77aa23a857cd8eb250617129d074478e1a5
2020/03/18 12:57:24 existing blob: sha256:e2c0fb34dff3a1d32346b92e53fb88a14d1987b402a2348cb379c039687fabe2
2020/03/18 12:57:25 pushed blob: sha256:b09e8ab3924377a759f2311cb97de89f24d0396d7509b4d3c23249f833a60f38
2020/03/18 12:57:25 pushed blob: sha256:7f627bf89a9b86c193f2bd3d45360d39f492a8eeb1a95eebde32c5428fa19e06
2020/03/18 12:57:25 pushed blob: sha256:05303d20f8ed58afecda55c067a395819739bfe55db7c99e97588b672f0d904d
2020/03/18 12:57:25 pushed blob: sha256:90c08719c1d4b023cfd6893a56b62cee2aaef6e0232a514bff5c8dd08592de16
2020/03/18 12:57:25 pushed blob: sha256:0ed7f52cc133f2d9bf1e9935383e63f62e0bdd7b394c5a28789fe7ea0f0678c8
2020/03/18 12:57:25 685249416972.dkr.ecr.ap-south-1.amazonaws.com/vicky-socs/test-python-jenkinsx:0.0.0-SNAPSHOT-PR-4-1: digest: sha256:1ce8d4b337495011fa9289382104f5da9d08afe9effec1ab696d2857fc8ed61e size: 2385

Showing logs for build [32mvicky-socs-test-python-jenkinsx-ct8sr-1[0m stage [32mfrom-build-pack[0m and container [32mstep-postbuild-post-build[0m
no CVE provider running in the current ** namespace so skip adding image to be analysed

Showing logs for build [32mvicky-socs-test-python-jenkinsx-ct8sr-1[0m stage [32mfrom-build-pack[0m and container [32mstep-promote-make-preview[0m
sed -i -e "s/version:.*/version: 0.0.0-SNAPSHOT-PR-4-1/" Chart.yaml
sed -i -e "s/version:.*/version: 0.0.0-SNAPSHOT-PR-4-1/" ../*/Chart.yaml
sed -i -e "s|repository:.*|repository: 685249416972.dkr.ecr.ap-south-1.amazonaws.com\/vicky-socs\/test-python-jenkinsx|" values.yaml
sed -i -e "s/tag:.*/tag: 0.0.0-SNAPSHOT-PR-4-1/" values.yaml
echo "  version: 0.0.0-SNAPSHOT-PR-4-1" >> requirements.yaml
** step helm build
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Adding missing Helm repo: storage.googleapis.com https://storage.googleapis.com/chartmuseum.jenkins-x.io
Successfully added Helm repository storage.googleapis.com.
Adding missing Helm repo: jenkins-x-chartmuseum http://jenkins-x-chartmuseum:8080
Successfully added Helm repository jenkins-x-chartmuseum.
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Adding missing Helm repo: chartmuseum.jenkins-x.io http://chartmuseum.jenkins-x.io
Successfully added Helm repository chartmuseum.jenkins-x.io.

Showing logs for build [32mvicky-socs-test-python-jenkinsx-ct8sr-1[0m stage [32mfrom-build-pack[0m and container [32mstep-promote-jx-preview[0m
Creating a preview
Created environment vicky-socs-test-python-jenkinsx-pr-4
Namespace **-vicky-socs-test-python-jenkinsx-pr-4 created 
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  config:
    domain: 3.7.28.134.nip.io
    exposer: Ingress
    http: "true"
preview:
  image:
    repository: 685249416972.dkr.ecr.ap-south-1.amazonaws.com/vicky-socs/test-python-jenkinsx
    tag: 0.0.0-SNAPSHOT-PR-4-1

Updating PipelineActivities vicky-socs-test-python-jenkinsx-pr-4-1 which has status Running
WARNING: preview application http://test-python-jenkinsx.**-vicky-socs-test-python-jenkinsx-pr-4.3.7.28.134.nip.io not available, error was 503 503 Service Temporarily Unavailable, delaying for: 1.070673276s
WARNING: preview application http://test-python-jenkinsx.**-vicky-socs-test-python-jenkinsx-pr-4.3.7.28.134.nip.io not available, error was 503 503 Service Temporarily Unavailable, delaying for: 1.195623845s
Preview application is now available at: http://test-python-jenkinsx.**-vicky-socs-test-python-jenkinsx-pr-4.3.7.28.134.nip.io
