
Showing logs for build [32mvicky-socs-test-python-jenkinsx-g9qt9-2[0m stage [32mfrom-build-pack[0m and container [32mstep-credential-initializer-rxnp9[0m
{"level":"warn","ts":1584535423.8863127,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1584535423.8868675,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mvicky-socs-test-python-jenkinsx-g9qt9-2[0m stage [32mfrom-build-pack[0m and container [32mstep-working-dir-initializer-lhkk4[0m
{"level":"warn","ts":1584535424.9337523,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1584535424.9348083,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}

Showing logs for build [32mvicky-socs-test-python-jenkinsx-g9qt9-2[0m stage [32mfrom-build-pack[0m and container [32mstep-place-tools[0m

Showing logs for build [32mvicky-socs-test-python-jenkinsx-g9qt9-2[0m stage [32mfrom-build-pack[0m and container [32mstep-git-source-vicky-socs-test-python-jenkinsx-g9qt9-8nwqm[0m
{"level":"warn","ts":1584535431.039793,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1584535433.5520246,"logger":"fallback-logger","caller":"git/git.go:103","msg":"Successfully cloned https://github.com/vicky-socs/test-python-jenkinsx.git @ v0.0.7 in path /workspace/source"}

Showing logs for build [32mvicky-socs-test-python-jenkinsx-g9qt9-2[0m stage [32mfrom-build-pack[0m and container [32mstep-git-merge[0m
Using SHAs from PULL_REFS=staging:fb592cbac6ae56aa5b0ff272a50ff662862269e2
WARNING: no SHAs to merge, falling back to initial cloned commit

Showing logs for build [32mvicky-socs-test-python-jenkinsx-g9qt9-2[0m stage [32mfrom-build-pack[0m and container [32mstep-setup-jx-git-credentials[0m
Generated Git credentials file /workspace/xdg_config/git/credentials

Showing logs for build [32mvicky-socs-test-python-jenkinsx-g9qt9-2[0m stage [32mfrom-build-pack[0m and container [32mstep-build-python-unittest[0m

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK

Showing logs for build [32mvicky-socs-test-python-jenkinsx-g9qt9-2[0m stage [32mfrom-build-pack[0m and container [32mstep-build-container-build[0m
[36mINFO[0m[0000] Downloading base image python:onbuild        
2020/03/18 12:43:57 No matching credentials were found, falling back on anonymous
[36mINFO[0m[0002] Error while retrieving image from cache: getting file info: stat /workspace/sha256:43780a8431c53f4afd734ad795e03127c0c607337a60639c5903a51a03535c22: no such file or directory 
[36mINFO[0m[0002] Downloading base image python:onbuild        
2020/03/18 12:43:59 No matching credentials were found, falling back on anonymous
[36mINFO[0m[0004] Executing 3 build triggers                   
[36mINFO[0m[0004] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0004] Checking for cached layer 685249416972.dkr.ecr.ap-south-1.amazonaws.com/todo/cache:20ed5631d983ab35ddcc4224cde40d34ba4dcc68c4ee26635bbf30d01c3c2af6... 
[36mINFO[0m[0004] Using caching version of cmd: RUN pip install --no-cache-dir -r requirements.txt 
[36mINFO[0m[0004] Using files from context: [/workspace/source] 
[36mINFO[0m[0004] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0004] cmd: EXPOSE                                  
[36mINFO[0m[0004] Adding exposed port: 8080/tcp                
[36mINFO[0m[0004] Skipping unpacking as no commands require it. 
[36mINFO[0m[0004] Taking snapshot of full filesystem...        
[36mINFO[0m[0004] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0004] COPY requirements.txt /usr/src/app/          
[36mINFO[0m[0004] Taking snapshot of files...                  
[36mINFO[0m[0004] RUN pip install --no-cache-dir -r requirements.txt 
[36mINFO[0m[0004] Found cached layer, extracting to filesystem 
[36mINFO[0m[0005] Taking snapshot of files...                  
[36mINFO[0m[0005] Using files from context: [/workspace/source] 
[36mINFO[0m[0005] COPY . /usr/src/app                          
[36mINFO[0m[0005] Taking snapshot of files...                  
[36mINFO[0m[0005] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0005] COPY requirements.txt .                      
[36mINFO[0m[0005] Taking snapshot of files...                  
[36mINFO[0m[0005] ENV PORT 8080                                
[36mINFO[0m[0005] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0005] EXPOSE 8080                                  
[36mINFO[0m[0005] cmd: EXPOSE                                  
[36mINFO[0m[0005] Adding exposed port: 8080/tcp                
[36mINFO[0m[0005] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0005] ENTRYPOINT ["python"]                        
[36mINFO[0m[0005] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0005] CMD ["app.py"]                               
[36mINFO[0m[0005] No files changed in this command, skipping snapshotting. 
2020/03/18 12:44:02 existing blob: sha256:1c7fe136a31e13a1c879245672184ced3b9fc590989ba42a522a57b071a9c1aa
2020/03/18 12:44:02 existing blob: sha256:e10b68fb77e6e91453cd4c1b02e2d77aa23a857cd8eb250617129d074478e1a5
2020/03/18 12:44:02 existing blob: sha256:490280dbcfb772eb5731f059e38fcfacaeb75b4d005af7c249fd51926db2bd62
2020/03/18 12:44:02 existing blob: sha256:ece825d3308bbf98f708d95475ccd880497a1e2979ff4ef2534d49049a18488f
2020/03/18 12:44:02 existing blob: sha256:06854774e2f35e4763103a446112c67322913a6177bea69eb49663e0166e6d6d
2020/03/18 12:44:02 existing blob: sha256:e2c0fb34dff3a1d32346b92e53fb88a14d1987b402a2348cb379c039687fabe2
2020/03/18 12:44:02 existing blob: sha256:f0db43b9b8da254cebc77bf871006df01219e195b9853616b9f708f124a00f3a
2020/03/18 12:44:02 existing blob: sha256:2d21c767035c4593de8bf7ad9781aa83ba110871d1a50871192f4e3480e6f11d
2020/03/18 12:44:02 existing blob: sha256:e96bc319bce0351d1157092352bc5f85f8800c745388e60e86d06dec99285b45
2020/03/18 12:44:03 pushed blob: sha256:2c088206670945fd0acaa375284c8959825e88a54d9898c83a53cacc17bcd2fb
2020/03/18 12:44:03 pushed blob: sha256:1464fa109ec1978e60df559e6fc1a8c27e644cb84b67f32300a825af0b3ad826
2020/03/18 12:44:03 pushed blob: sha256:34e7bdb28af36dddbae07895103bb753b918b78c5c6eb75b785712c16b564cb3
2020/03/18 12:44:03 pushed blob: sha256:ae91bb8dea75d983df6fc2b0ed505235894bae483a1b62f5d39195ce91bab9fc
2020/03/18 12:44:03 pushed blob: sha256:6e43e7f1a3820ea189db11366fbbc58bfc8b31307d3380ed56eda7232d1f3cc1
2020/03/18 12:44:03 685249416972.dkr.ecr.ap-south-1.amazonaws.com/vicky-socs/test-python-jenkinsx:0.0.7: digest: sha256:67c1b97853120e1b6c0171beb5cc37d4931daf22fa2f9e3789a48194a9fcf0d9 size: 2385

Showing logs for build [32mvicky-socs-test-python-jenkinsx-g9qt9-2[0m stage [32mfrom-build-pack[0m and container [32mstep-build-post-build[0m
no CVE provider running in the current ** namespace so skip adding image to be analysed

Showing logs for build [32mvicky-socs-test-python-jenkinsx-g9qt9-2[0m stage [32mfrom-build-pack[0m and container [32mstep-promote-changelog[0m
Converted /workspace/source/charts/test-python-jenkinsx to an unshallow repository
Generating change log from git ref 24fe81a00e1a15dbe2b2c3e759d5875825847ec9 => ea55d2e3f11f970839464b28c163e56a0a1c342e
Associating user x-0 in users.jenkins.io with email jenkins-x@googlegroups.com to git GitProvider user with login -0 as emails match
Adding label jenkins.io/git-github-userid=-0 to user x-0 in users.jenkins.io
WARNING: Failed to enrich commit a6a65db7d4a9ccbfcfa7b0ddd94d461ce44f19ae with issues: User.jenkins.io "x-0" is invalid: metadata.labels: Invalid value: "-0": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
Associating user x-0 in users.jenkins.io with email jenkins-x@googlegroups.com to git GitProvider user with login -0 as emails match
Adding label jenkins.io/git-github-userid=-0 to user x-0 in users.jenkins.io
WARNING: Failed to enrich commit a6a65db7d4a9ccbfcfa7b0ddd94d461ce44f19ae with issues: User.jenkins.io "x-0" is invalid: metadata.labels: Invalid value: "-0": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
Finding issues in commit messages using git format
WARNING: No release found for vicky-socs/test-python-jenkinsx and tag v0.0.7 so creating a new release
Updated the release information at https://github.com/vicky-socs/test-python-jenkinsx/releases/tag/v0.0.7
generated: /workspace/source/charts/test-python-jenkinsx/templates/release.yaml
Created Release test-python-jenkinsx-0-0-7 resource in namespace **
Updating PipelineActivity vicky-socs-test-python-jenkinsx-staging-2 with version 0.0.7
Updated PipelineActivities vicky-socs-test-python-jenkinsx-staging-2 with release notes URL: https://github.com/vicky-socs/test-python-jenkinsx/releases/tag/v0.0.7

Showing logs for build [32mvicky-socs-test-python-jenkinsx-g9qt9-2[0m stage [32mfrom-build-pack[0m and container [32mstep-promote-helm-release[0m
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Adding missing Helm repo: storage.googleapis.com https://storage.googleapis.com/chartmuseum.jenkins-x.io
Successfully added Helm repository storage.googleapis.com.
Adding missing Helm repo: jenkins-x-chartmuseum http://jenkins-x-chartmuseum:8080
Successfully added Helm repository jenkins-x-chartmuseum.
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Uploading chart file test-python-jenkinsx-0.0.7.tgz to http://jenkins-x-chartmuseum:8080/api/charts
Received 201 response: {"saved":true}

Showing logs for build [32mvicky-socs-test-python-jenkinsx-g9qt9-2[0m stage [32mfrom-build-pack[0m and container [32mstep-promote-jx-promote[0m
WARNING: prow based install so skip waiting for the merge of Pull Requests to go green as currently there is an issue with gettingstatuses from the PR, see https://github.com/jenkins-x/**/issues/2410
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Promoting app test-python-jenkinsx version 0.0.7 to namespace **-staging
WARNING: 
Created Pull Request: https://github.com/vicky-socs/environment-non-prod-cluster-staging/pull/7
Added label updatebot to Pull Request https://github.com/vicky-socs/environment-non-prod-cluster-staging/pull/7
got git provider status pending from PR https://github.com/vicky-socs/environment-non-prod-cluster-staging/pull/7
got git provider status pending from PR https://github.com/vicky-socs/environment-non-prod-cluster-staging/pull/7
got git provider status pending from PR https://github.com/vicky-socs/environment-non-prod-cluster-staging/pull/7
got git provider status pending from PR https://github.com/vicky-socs/environment-non-prod-cluster-staging/pull/7
got git provider status pending from PR https://github.com/vicky-socs/environment-non-prod-cluster-staging/pull/7
Pull Request https://github.com/vicky-socs/environment-non-prod-cluster-staging/pull/7 is merged at sha 3ddc0ec71c9887a5edebe44455e3399b0e96d285
Pull Request merged but we are not waiting for the update pipeline to complete!
