
Showing logs for build [32mvicky-socs-test-python-jenkinsx-9zvz6-1[0m stage [32mfrom-build-pack[0m and container [32mstep-credential-initializer-vpgbs[0m
{"level":"warn","ts":1584629645.1469133,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1584629645.1471844,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mvicky-socs-test-python-jenkinsx-9zvz6-1[0m stage [32mfrom-build-pack[0m and container [32mstep-working-dir-initializer-c9kwm[0m
{"level":"warn","ts":1584629646.1597118,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1584629646.1616044,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}

Showing logs for build [32mvicky-socs-test-python-jenkinsx-9zvz6-1[0m stage [32mfrom-build-pack[0m and container [32mstep-place-tools[0m

Showing logs for build [32mvicky-socs-test-python-jenkinsx-9zvz6-1[0m stage [32mfrom-build-pack[0m and container [32mstep-git-source-vicky-socs-test-python-jenkinsx-9zvz6-nsn5f[0m
{"level":"warn","ts":1584629652.292568,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1584629654.8271875,"logger":"fallback-logger","caller":"git/git.go:103","msg":"Successfully cloned https://github.com/vicky-socs/test-python-jenkinsx.git @ master in path /workspace/source"}

Showing logs for build [32mvicky-socs-test-python-jenkinsx-9zvz6-1[0m stage [32mfrom-build-pack[0m and container [32mstep-git-merge[0m
Using SHAs from PULL_REFS=staging:bd2f21911ba3b2262f1409e744aecd543f194cd8,14:63ef61aca74b95a80d48282ee3b8d65f484c49be
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git fetch origin --unshallow 63ef61aca74b95a80d48282ee3b8d65f484c49be: bd2f21911ba3b2262f1409e744aecd543f194cd8:
DEBUG: ran git fetch --unshallow origin 63ef61aca74b95a80d48282ee3b8d65f484c49be: bd2f21911ba3b2262f1409e744aecd543f194cd8: in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git branch
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git branch staging
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git checkout staging
DEBUG: ran git checkout staging in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git reset --hard bd2f21911ba3b2262f1409e744aecd543f194cd8
DEBUG: ran git reset --hard bd2f21911ba3b2262f1409e744aecd543f194cd8 in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git clean -fd .
DEBUG: ran clean --force -d . in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git merge 63ef61aca74b95a80d48282ee3b8d65f484c49be
DEBUG: ran git merge 63ef61aca74b95a80d48282ee3b8d65f484c49be in 
DEBUG: LC_ALL=C JX_LOG_LEVEL=error git log --format=%H%x1f%an%x1f%ae%x1f%cn%x1f%ce%x1f%s%n%b%x1e bd2f21911ba3b2262f1409e744aecd543f194cd8..HEAD
Merged SHA b7638fd39bc6aceea551fa44e86b4e6f039c3d7f with commit message 'Merge commit '63ef61aca74b95a80d48282ee3b8d65f484c49be' into staging' into base branch staging
Merged SHA 63ef61aca74b95a80d48282ee3b8d65f484c49be with commit message 'count 5' into base branch staging

Showing logs for build [32mvicky-socs-test-python-jenkinsx-9zvz6-1[0m stage [32mfrom-build-pack[0m and container [32mstep-build-python-unittest[0m

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK

Showing logs for build [32mvicky-socs-test-python-jenkinsx-9zvz6-1[0m stage [32mfrom-build-pack[0m and container [32mstep-build-container-build[0m
[36mINFO[0m[0000] Downloading base image python:onbuild        
2020/03/19 14:54:18 No matching credentials were found, falling back on anonymous
[36mINFO[0m[0002] Error while retrieving image from cache: getting file info: stat /workspace/sha256:43780a8431c53f4afd734ad795e03127c0c607337a60639c5903a51a03535c22: no such file or directory 
[36mINFO[0m[0002] Downloading base image python:onbuild        
2020/03/19 14:54:21 No matching credentials were found, falling back on anonymous
[36mINFO[0m[0004] Executing 3 build triggers                   
[36mINFO[0m[0004] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0004] Checking for cached layer 685249416972.dkr.ecr.ap-south-1.amazonaws.com/todo/cache:20ed5631d983ab35ddcc4224cde40d34ba4dcc68c4ee26635bbf30d01c3c2af6... 
[36mINFO[0m[0004] Using caching version of cmd: RUN pip install --no-cache-dir -r requirements.txt 
[36mINFO[0m[0004] Using files from context: [/workspace/source] 
[36mINFO[0m[0004] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0004] cmd: EXPOSE                                  
[36mINFO[0m[0004] Adding exposed port: 8080/tcp                
[36mINFO[0m[0004] Skipping unpacking as no commands require it. 
[36mINFO[0m[0004] Taking snapshot of full filesystem...        
[36mINFO[0m[0004] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0004] COPY requirements.txt /usr/src/app/          
[36mINFO[0m[0004] Taking snapshot of files...                  
[36mINFO[0m[0004] RUN pip install --no-cache-dir -r requirements.txt 
[36mINFO[0m[0004] Found cached layer, extracting to filesystem 
[36mINFO[0m[0004] Taking snapshot of files...                  
[36mINFO[0m[0005] Using files from context: [/workspace/source] 
[36mINFO[0m[0005] COPY . /usr/src/app                          
[36mINFO[0m[0005] Taking snapshot of files...                  
[36mINFO[0m[0005] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0005] COPY requirements.txt .                      
[36mINFO[0m[0005] Taking snapshot of files...                  
[36mINFO[0m[0005] ENV PORT 8080                                
[36mINFO[0m[0005] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0005] EXPOSE 8080                                  
[36mINFO[0m[0005] cmd: EXPOSE                                  
[36mINFO[0m[0005] Adding exposed port: 8080/tcp                
[36mINFO[0m[0005] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0005] ENTRYPOINT ["python"]                        
[36mINFO[0m[0005] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0005] CMD ["app.py"]                               
[36mINFO[0m[0005] No files changed in this command, skipping snapshotting. 
2020/03/19 14:54:24 existing blob: sha256:2d21c767035c4593de8bf7ad9781aa83ba110871d1a50871192f4e3480e6f11d
2020/03/19 14:54:24 existing blob: sha256:06854774e2f35e4763103a446112c67322913a6177bea69eb49663e0166e6d6d
2020/03/19 14:54:24 existing blob: sha256:e2c0fb34dff3a1d32346b92e53fb88a14d1987b402a2348cb379c039687fabe2
2020/03/19 14:54:24 existing blob: sha256:e10b68fb77e6e91453cd4c1b02e2d77aa23a857cd8eb250617129d074478e1a5
2020/03/19 14:54:24 existing blob: sha256:e96bc319bce0351d1157092352bc5f85f8800c745388e60e86d06dec99285b45
2020/03/19 14:54:24 existing blob: sha256:f0db43b9b8da254cebc77bf871006df01219e195b9853616b9f708f124a00f3a
2020/03/19 14:54:24 existing blob: sha256:1c7fe136a31e13a1c879245672184ced3b9fc590989ba42a522a57b071a9c1aa
2020/03/19 14:54:24 existing blob: sha256:ece825d3308bbf98f708d95475ccd880497a1e2979ff4ef2534d49049a18488f
2020/03/19 14:54:24 existing blob: sha256:490280dbcfb772eb5731f059e38fcfacaeb75b4d005af7c249fd51926db2bd62
2020/03/19 14:54:24 pushed blob: sha256:841d94effc7c7decb8f8d4e99870ca753814276959fc79bc289ec1e2b5cc98ba
2020/03/19 14:54:24 pushed blob: sha256:128255651d035b43c8f28759c7cf1aedf9efd97fd389e5c3be1769a654c6dda9
2020/03/19 14:54:24 pushed blob: sha256:c1dac07c896b700c0a640621d0613071369b71b89ce7491b4b2016b3b5f0b77a
2020/03/19 14:54:24 pushed blob: sha256:0841a713f0373dca7251117e3249a229daa4fe05240c620d7ca6053cc3fa0119
2020/03/19 14:54:24 pushed blob: sha256:4995ca856ebc150046f590b7dfbf9865facbe06840bf83dc02c030986a416221
2020/03/19 14:54:25 685249416972.dkr.ecr.ap-south-1.amazonaws.com/vicky-socs/test-python-jenkinsx:0.0.0-SNAPSHOT-PR-14-1: digest: sha256:4ed6acb4ef15cc2c345e98bb72ca1a9074fc8d232ffe1c1de10823ccfd8dd912 size: 2385

Showing logs for build [32mvicky-socs-test-python-jenkinsx-9zvz6-1[0m stage [32mfrom-build-pack[0m and container [32mstep-postbuild-post-build[0m
no CVE provider running in the current ** namespace so skip adding image to be analysed

Showing logs for build [32mvicky-socs-test-python-jenkinsx-9zvz6-1[0m stage [32mfrom-build-pack[0m and container [32mstep-promote-make-preview[0m
sed -i -e "s/version:.*/version: 0.0.0-SNAPSHOT-PR-14-1/" Chart.yaml
sed -i -e "s/version:.*/version: 0.0.0-SNAPSHOT-PR-14-1/" ../*/Chart.yaml
sed -i -e "s|repository:.*|repository: 685249416972.dkr.ecr.ap-south-1.amazonaws.com\/vicky-socs\/test-python-jenkinsx|" values.yaml
sed -i -e "s/tag:.*/tag: 0.0.0-SNAPSHOT-PR-14-1/" values.yaml
echo "  version: 0.0.0-SNAPSHOT-PR-14-1" >> requirements.yaml
** step helm build
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Adding missing Helm repo: storage.googleapis.com https://storage.googleapis.com/chartmuseum.jenkins-x.io
Successfully added Helm repository storage.googleapis.com.
Adding missing Helm repo: jenkins-x-chartmuseum http://jenkins-x-chartmuseum:8080
Successfully added Helm repository jenkins-x-chartmuseum.
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Adding missing Helm repo: chartmuseum.jenkins-x.io http://chartmuseum.jenkins-x.io
Successfully added Helm repository chartmuseum.jenkins-x.io.

Showing logs for build [32mvicky-socs-test-python-jenkinsx-9zvz6-1[0m stage [32mfrom-build-pack[0m and container [32mstep-promote-jx-preview[0m
Creating a preview
Created environment vicky-socs-test-python-jenkinsx-pr-14
Namespace **-vicky-socs-test-python-jenkinsx-pr-14 created 
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  config:
    domain: 3.6.244.161.nip.io
    exposer: Ingress
    http: "true"
preview:
  image:
    repository: 685249416972.dkr.ecr.ap-south-1.amazonaws.com/vicky-socs/test-python-jenkinsx
    tag: 0.0.0-SNAPSHOT-PR-14-1

Updating PipelineActivities vicky-socs-test-python-jenkinsx-pr-14-1 which has status Running
Preview application is now available at: http://test-python-jenkinsx.**-vicky-socs-test-python-jenkinsx-pr-14.3.6.244.161.nip.io
